server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/clients/** to insurance-service
        - id: insurance-service-clients-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: insurance-service-cars-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/cars/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: insurance-service-drivers-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/drivers/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: insurance-service-policies-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api/policies/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/clients to insurance-service /v3/api-docs
        - id: api-docs-client-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api-docs/clients
          filters:
            - RewritePath=/api-docs/clients,/v3/api-docs

        - id: api-docs-client-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api-docs/cars
          filters:
            - RewritePath=/api-docs/cars,/v3/api-docs

        - id: api-docs-client-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api-docs/drivers
          filters:
            - RewritePath=/api-docs/drivers,/v3/api-docs

        - id: api-docs-client-route
          uri: http://insurance-service:4000
          predicates:
            - Path=/api-docs/policies
          filters:
            - RewritePath=/api-docs/policies,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs